### PR TITLE
Remove D3_GAMEDIR hard-coded CMake variable

### PR DESCRIPTION
**Pull request by Lgt2x**
Proper standalone installation will come later

### CODE REVIEW

**Comment by GravisZro** [comment]
Since not everyone is skilled with cmake, it should have a fallback value if not set via commandline.

**Comment by Lgt2x** [comment]
> Since not everyone is skilled with cmake, it should have a fallback value if not set via commandline.

The plan has changed, we're postponing reworking the install procedure until we do proper packaging. Until them, we'll provide instructions to the user to copy the generated executable to the right location

**Comment by Lgt2x** [comment]
We should be ready for review now. This just gets rid of the default D3_GAMEDIR

**Review by Arcnor — APPROVED** [review]
Only thing that I might change is not removing the newline at the end of every CMakeList file, but other than that just merge whenever you want, looks fine 🙂

**Comment by Lgt2x** [comment]
> Only thing that I might change is not removing the newline at the end of every CMakeList file, but other than that just merge whenever you want, looks fine 🙂

Not sure what my editor did there, but it's fixed now

**Pull request merged**
