### PR TITLE
Accurately find the linux artifacts

### PR DESCRIPTION
**Pull request by JeodC**
This workflow excludes the build_type matrix when searching for the linux artifact path.

### CODE REVIEW

**Comment by JeodC** [comment]
I think Linux does not use Debug and Release, correct? So building twice for Linux is redundant?

**Comment by th1000s** [comment]
Release / Debug in cmake also adds `-g` or `-O` flags on Linux, even `-O3` at the moment. Some warnings are only triggered on a certain optimization level.

But it might be interesting to build with `clang` on Linux as well.

**Comment by winterheart** [comment]
```
            "generator": "Ninja Multi-Config",
```
For linux in CMakePresets.json unifies all builds, better using this.

**Comment by JeodC** [comment]
This should be ok to squash and merge now.

**Pull request merged**
