### PR TITLE
Change case sensitivity

### PR DESCRIPTION
**Pull request by JeodC**
Converts all directories and files to lowercase except for top level files. May have conflicts with some recent commits--resolve manually. This was done via python script:

```python
import os

def convert_to_lowercase(directory):
    for root, dirs, files in os.walk(directory):
        for file in files:
            original_path = os.path.join(root, file)
            lowercase_path = original_path.lower()
            if original_path != lowercase_path:
                os.rename(original_path, lowercase_path)
                print(f"Renamed '{original_path}' to '{lowercase_path}'")
        for dir in dirs:
            original_path = os.path.join(root, dir)
            lowercase_path = original_path.lower()
            if original_path != lowercase_path:
                os.rename(original_path, lowercase_path)
                print(f"Renamed '{original_path}' to '{lowercase_path}'")

if __name__ == "__main__":
    script_dir = os.path.dirname(os.path.abspath(__file__))
    convert_to_lowercase(script_dir)
```

Ignore this PR if you want, it's a preference thing. Looking through the `scripts` directory was particularly annoying as there are `Levelxxx.cpp` and `levelxxx.cpp` files. ;)

### CODE REVIEW

**Comment by JeodC** [comment]
Looks like #19 was committed after I forked, so would need re-committing ig.

**Comment by JeodC** [comment]
I have added the missing commit to `.clang-format` and removed what appeared to be a tmp file `#.clang-format#`.

**Comment by winterheart** [comment]
CMakeLists.txt also renamed which shouldn't be. I think main idea is rename project files, if so, there should be file mask on *.cpp, *.CPP, *.c, *.C, *.h, *.H.

**Comment by JeodC** [comment]
> CMakeLists.txt also renamed which shouldn't be. I think main idea is rename project files, if so, there should be file mask on *.cpp, *.CPP, *.c, *.C, *.h, *.H.

Yes, this was quick n' dirty. If you'd like to do this along with your clang formatting, go ahead.

**Comment by JeodC** [comment]
This is now fixed.

**Pull request closed without merging**
